#!/bin/bash

export CFLAGS="-march=pentium3 -O2 -pipe -fomit-frame-pointer -fprefetch-loop-arrays"


cd em-game

aclocal-1.8
automake-1.8
autoconf-2.58
./configure

cd ../em-tools

aclocal-1.8
automake-1.8
autoconf-2.58
./configure

cd ../misc

aclocal-1.8
automake-1.8
autoconf-2.58
./configure

cd ../
