#!/bin/bash

ln -sfn / ../stage3s/current-stage3
#export CFLAGS="-march=i686 -O0 -pipe -g -fomit-frame-pointer -fprefetch-loop-arrays"
export CFLAGS="-march=i686 -O3 -pipe -fomit-frame-pointer -fprefetch-loop-arrays"
#export CFLAGS="-march=i686 -O3 -pipe -fprefetch-loop-arrays"
#export CC="/home/jonny/Desktop/apbuild-1.5/apgcc"
export APBUILD_NO_STATIC_X=1

cd em-game

make distclean

aclocal-1.8
automake-1.8
autoconf-2.59
./configure --enable-nonauthenticating
#./configure

cd ../em-tools

make distclean

aclocal-1.8
automake-1.8
autoconf-2.59
./configure

cd ../misc

make distclean

aclocal-1.8
automake-1.8
autoconf-2.59
./configure

cd ../
