#define OBJECTTYPE_PLASMACANNON		0
#define OBJECTTYPE_MINIGUN			1
#define OBJECTTYPE_ROCKETLAUNCHER	2
#define OBJECTTYPE_RAILS			3
#define OBJECTTYPE_SHIELDENERGY		4
#define OBJECTTYPE_SPAWNPOINT		5
#define OBJECTTYPE_SPEEDUPRAMP		6
#define OBJECTTYPE_TELEPORTER 		7
#define OBJECTTYPE_GRAVITYWELL		8

#define TELEPORTER_ROTATION_TYPE_ABS	0
#define TELEPORTER_ROTATION_TYPE_REL	1
