#!/bin/bash -v


export CC="/home/jonny/Desktop/apbuild-1.5/apgcc"
export APBUILD_NO_STATIC_X=1
export CFLAGS="-march=i686 -O3 -pipe -fomit-frame-pointer"

rm -rf SDL-1.2.7
tar xzf SDL-1.2.7.tar.gz

cd SDL-1.2.7

cat ../1.2.7-nobuggy-X.patch|patch -p1
cat ../1.2.7-libcaca.patch|patch -p1
cat ../1.2.7-gcc34.patch|patch -p0
cat ../1.2.7-joystick2.patch|patch -p0
cat ../1.2.7-26headers.patch|patch -p1


aclocal-1.8
automake-1.8
autoconf-2.59

./configure --disable-debug --enable-audio --disable-video --disable-joystick --disable-cdrom --enable-threads --enable-timers --enable-endian --disable-file --enable-cpuinfo --enable-oss --enable-alsa --enable-esd --disable-esdtest --enable-esd-shared --enable-arts --enable-arts-shared --enable-pthreads --enable-sigaction --prefix=`pwd`/image

make install
